name: API Automation CI - Credit & Balance

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código do repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java 21 (igual ao seu ambiente local)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Executa os testes automatizados via Maven
      - name: Run Tests with Maven
        run: mvn clean test
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }} # Passa o token seguro via GitHub Secrets

      # 4. Salva o relatório HTML do Cucumber gerado nos artefatos da pipeline
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports.html